# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-14 12:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('deleted_time', models.DateTimeField(blank=True, null=True, verbose_name='deleted time')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('attach_file', models.FileField(upload_to='messages/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', '3gp', 'wmv', 'webm', 'flv', 'mpeg'])], verbose_name='attach_file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'MessageAttachment',
                'verbose_name_plural': 'MessageAttachments',
            },
        ),
        migrations.CreateModel(
            name='MessageBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('deleted_time', models.DateTimeField(blank=True, null=True, verbose_name='deleted time')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('body', lib.fields.FarsiTextField(verbose_name='body')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('attachments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.MessageAttachment', verbose_name='attachment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_messages', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'MessageBody',
                'verbose_name_plural': 'MessageBodies',
            },
        ),
    ]
