# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-25 07:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20190925_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='attach_file',
            field=models.FileField(upload_to='messages/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', '3gp', 'wmv', 'webm', 'flv', 'mpeg', 'jpg', 'png', 'jpeg'])], verbose_name='attach_file'),
        ),
    ]
