# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-25 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20190925_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagebody',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
