# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20190930_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='messagebody',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='deleted'),
        ),
    ]
